from typing import Annotated, Any

import numpy as np

from satellite.models import ImagingTask, SatelliteTelemetry, SlewTask
from validated import (
    Check,
    DType,
    GreaterThan,
    InRange,
    Length,
    LessThan,
    MatchesPattern,
    Shape,
    validated,
)


# 1. Base function to check reaction wheel array shapes and types
@validated
def check_reaction_wheels(
    wheel_speeds: Annotated[np.ndarray, Shape(3), DType(np.float64)],
) -> bool:
    return True


# 2. Validation function for Charging Mode
@validated
def validate_charging_telemetry(
    panels_deployed: Annotated[bool, Check(lambda x: x is True, "all solar panels must be deployed")],
    net_power: Annotated[float, GreaterThan(0.0)],
    battery_status: Annotated[str, Check(lambda s: s == "charging", "battery status must be 'charging'")],
    battery_charge_level: Annotated[float, InRange(50.0, 100.0)],
    sun_pointing_deviation: Annotated[float, LessThan(5.0)],
    reaction_wheel_speeds: Annotated[np.ndarray, Shape(3), DType(np.float64)],
) -> bool:
    return True


# 3. Validation function for Data Collection Mode
@validated
def validate_data_collection_telemetry(
    battery_temperature: Annotated[float, InRange(-10.0, 40.0)],
    ground_station_visible: Annotated[bool, Check(lambda x: x is True, "ground station must be visible")],
    power_margin: Annotated[float, GreaterThan(0.0)],  # Margin between max draw and current draw
    battery_charge_level: Annotated[float, InRange(50.0, 100.0)],
    target_pointing_deviation: Annotated[float, LessThan(1.0)],
    reaction_wheel_speeds: Annotated[np.ndarray, Shape(3), DType(np.float64)],
) -> bool:
    return True


def check_telemetry(telemetry: SatelliteTelemetry, max_battery_draw: float = 150.0) -> bool:
    """
    Ingests and checks a telemetry packet from the satellite.
    Raises ValidationError if any rule for the current mode is violated.
    """
    # Verify reaction wheel speeds are healthy across all modes
    check_reaction_wheels(telemetry.acs.reaction_wheel_speeds)

    if telemetry.mode == "charging":
        # Check if all solar panels are deployed
        panels_deployed = all(p.deployed for p in telemetry.panels)

        # Calculate total power generated by the panels
        total_gen = sum(p.power_generated for p in telemetry.panels)

        # Net power = generated - consumed (which is battery.current_draw when charging/consuming)
        net_power = total_gen - telemetry.battery.current_draw

        return validate_charging_telemetry(
            panels_deployed=panels_deployed,
            net_power=net_power,
            battery_status=telemetry.battery.status,
            battery_charge_level=telemetry.battery.charge_level,
            sun_pointing_deviation=telemetry.acs.pointing_deviation,
            reaction_wheel_speeds=telemetry.acs.reaction_wheel_speeds,
        )

    elif telemetry.mode == "data_collection":
        # Current draw must not exceed the max draw allowed by the battery
        power_margin = max_battery_draw - telemetry.battery.current_draw

        return validate_data_collection_telemetry(
            battery_temperature=telemetry.battery.temperature,
            ground_station_visible=telemetry.comms.ground_station_visible,
            power_margin=power_margin,
            battery_charge_level=telemetry.battery.charge_level,
            target_pointing_deviation=telemetry.acs.pointing_deviation,
            reaction_wheel_speeds=telemetry.acs.reaction_wheel_speeds,
        )

    # Safe or default mode: no additional constraints
    return True


# 4. Example of selective validation levels (Full validation, Type-only, and No validation)
@validated
def validate_subsystem_diagnostics(
    # Full validation: coerced to str + matched against regex pattern
    subsystem_id: Annotated[str, MatchesPattern(r"^(ACS|PWR|COM)-\d{3}$")],
    # Type-only validation: coerced to float, no value/range constraints checked
    temperature_offset: float,
    # No validation: completely skipped (no type coercion, no checks)
    raw_telemetry: Any,
) -> bool:
    """
    Demonstrates the three different validation subsets:
    - Full: type safety and custom constraints.
    - Type-only: type safety via coercion, but no constraints.
    - None: bypassed completely by the decorator.
    """
    return True


# 5. Slew Task pre-commit validation (decorator approach — kept for comparison)
# NOTE: With Pydantic integration, these functions are no longer strictly needed
# for SlewTask/ImagingTask because the models now self-validate at construction.
# They are kept here to demonstrate the @validated decorator approach side-by-side.
@validated
def validate_slew_task(
    poi_name: Annotated[str, Length(min_len=1)],
    max_slew_speed: Annotated[float, LessThan(2.0)],  # Max 2 deg/s speed
    predicted_coverage: Annotated[float, InRange(80.0, 100.0)],  # Min 80% coverage
) -> bool:
    return True


# 6. Imaging Task pre-commit validation (decorator approach — kept for comparison)
@validated
def validate_imaging_task(
    target_poi: Annotated[str, Length(min_len=1)],
    exposure_time: Annotated[float, InRange(0.01, 5.0)],  # 10ms to 5s
    cloud_cover_limit: Annotated[float, LessThan(20.0)],  # Max 20% cloud cover
    spectral_bands: Annotated[list[str], Length(min_len=1, max_len=5)],  # 1 to 5 bands
) -> bool:
    return True


# 7. Unified entry point for task safety checking
# With Pydantic integration, tasks are validated at construction time.
# This function is now a thin wrapper — if the task was constructed successfully,
# it has already passed validation. We keep it as a unified API entry point.
def validate_task(task: SlewTask | ImagingTask) -> bool:
    """
    Validates a task before it is committed to the spacecraft command queue.

    With Pydantic integration on the task models, validation happens automatically
    at construction time. This function exists as a unified API entry point and
    can be extended with cross-field or inter-model validation logic.
    """
    if isinstance(task, (SlewTask, ImagingTask)):
        return True
    raise ValueError(f"Unknown task type: {type(task)}")
