from typing import Annotated
import numpy as np
from constraints import (
    constrained,
    GreaterThan,
    LessThan,
    InRange,
    Check,
    Shape,
    DType,
)
from satellite.models import SatelliteTelemetry

# 1. Base function to check reaction wheel array shapes and types
@constrained
def check_reaction_wheels(
    wheel_speeds: Annotated[np.ndarray, Shape(3), DType(np.float64)]
) -> bool:
    return True

# 2. Validation function for Charging Mode
@constrained
def validate_charging_telemetry(
    panels_deployed: Annotated[bool, Check(lambda x: x is True, "all solar panels must be deployed")],
    net_power: Annotated[float, GreaterThan(0.0)],
    battery_status: Annotated[str, Check(lambda s: s == "charging", "battery status must be 'charging'")],
    battery_charge_level: Annotated[float, InRange(50.0, 100.0)],
    sun_pointing_deviation: Annotated[float, LessThan(5.0)],
    reaction_wheel_speeds: Annotated[np.ndarray, Shape(3), DType(np.float64)],
) -> bool:
    return True

# 3. Validation function for Data Collection Mode
@constrained
def validate_data_collection_telemetry(
    battery_temperature: Annotated[float, InRange(-10.0, 40.0)],
    ground_station_visible: Annotated[bool, Check(lambda x: x is True, "ground station must be visible")],
    power_margin: Annotated[float, GreaterThan(0.0)], # Margin between max draw and current draw
    battery_charge_level: Annotated[float, InRange(50.0, 100.0)],
    target_pointing_deviation: Annotated[float, LessThan(1.0)],
    reaction_wheel_speeds: Annotated[np.ndarray, Shape(3), DType(np.float64)],
) -> bool:
    return True


def check_telemetry(telemetry: SatelliteTelemetry, max_battery_draw: float = 150.0) -> bool:
    """
    Ingests and checks a telemetry packet from the satellite.
    Raises ConstraintValidationError if any rule for the current mode is violated.
    """
    # Verify reaction wheel speeds are healthy across all modes
    check_reaction_wheels(telemetry.acs.reaction_wheel_speeds)
    
    if telemetry.mode == "charging":
        # Check if all solar panels are deployed
        panels_deployed = all(p.deployed for p in telemetry.panels)
        
        # Calculate total power generated by the panels
        total_gen = sum(p.power_generated for p in telemetry.panels)
        
        # Net power = generated - consumed (which is battery.current_draw when charging/consuming)
        net_power = total_gen - telemetry.battery.current_draw
        
        return validate_charging_telemetry(
            panels_deployed=panels_deployed,
            net_power=net_power,
            battery_status=telemetry.battery.status,
            battery_charge_level=telemetry.battery.charge_level,
            sun_pointing_deviation=telemetry.acs.pointing_deviation,
            reaction_wheel_speeds=telemetry.acs.reaction_wheel_speeds,
        )
        
    elif telemetry.mode == "data_collection":
        # Current draw must not exceed the max draw allowed by the battery
        power_margin = max_battery_draw - telemetry.battery.current_draw
        
        return validate_data_collection_telemetry(
            battery_temperature=telemetry.battery.temperature,
            ground_station_visible=telemetry.comms.ground_station_visible,
            power_margin=power_margin,
            battery_charge_level=telemetry.battery.charge_level,
            target_pointing_deviation=telemetry.acs.pointing_deviation,
            reaction_wheel_speeds=telemetry.acs.reaction_wheel_speeds,
        )
    
    # Safe or default mode: no additional constraints
    return True
